name: vscode-insiders-release

on:
  push:
    tags:
      - vscode-v* # automatically create a new insider build with a release
  workflow_dispatch:

jobs:
  release:
    if: (startsWith(github.ref, 'refs/tags/vscode-v') || github.event_name == 'workflow_dispatch') && github.repository == 'PriNova/Cody-Community-Edition'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get all tags
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # SECURITY: pin third-party action hashes
        with:
          run_install: true
      - run: pnpm build
      - run: CODY_RELEASE_TYPE=insiders pnpm -C vscode run release:dry-run
      
      - name: Get tag message
        id: tag
        run: |
          echo "message<<EOF" >> $GITHUB_OUTPUT
          git tag -l --format='%(contents)' ${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./vscode/dist/cody-community.vsix
          name: "Release community-builds ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.tag.outputs.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}